//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_2hands.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int id { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<double> productPrice { get; set; }
        public string productName { get; set; }
        public string productImage { get; set; }
        public string status { get; set; }
        public string userName { get; set; }
        public string userAddress { get; set; }
        public string userPhone { get; set; }
        public string userEmail { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
